### ISSUE TITLE
Demo app build fail in IOS device

### ISSUE THREAD

**Issue by KwanghoLee** [introlab/ros_for_ios#5]
succes :  build in simulator6.1
fail :  build in IOS device

====error log   =======
Undefined symbols for architecture armv7:
  "_libiconv", referenced from:
      _apr_xlate_open in log4cxx(xlate.o)
      _apr_xlate_conv_buffer in log4cxx(xlate.o)
  "_libiconv_open", referenced from:
      _apr_xlate_open in log4cxx(xlate.o)
  "_libiconv_close", referenced from:
      _apr_xlate_open in log4cxx(xlate.o)
      _apr_xlate_cleanup in log4cxx(xlate.o)
ld: symbol(s) not found for architecture armv7
# clang: error: linker command failed with exit code 1 (use -v to see invocation)

how to build by IOS device??

Please help.....

thankU

**Comment by Ronan0912** [comment]
Hi,

It's a problem with the iconv library which provides an iconv() implementation for encoding conversions. This library is used by log4cxx and must be linked in a ros_for_ios project. In the demo_app Xcode project, the dynamic library "libiconv.2.4.0.dylib" is linked but it's possible that your system doesn't have the library for the armv7 (or is at a different location...). If it is the case, this library should be in red in the Xcode explorer.

You can try to add by yourself the iconv library :
- Go to the project properties
- Click on the ros_ios target
- Click on the "Build Phases" tab
- In the "Link Binary With Libraries" section delete the iconv library
- Add your own version

Keep me informed,

Ronan

**Comment by KwanghoLee** [comment]
thank you for your answer
 I already add 'libiconv.2.4.0.dylib', But build failed.
Simulater is working well, But device is not working.
What is diffrent???

**Comment by Ronan0912** [comment]
It's not the same libraries between the simulator and an iOS device. The simulator is an i386 platform while the iOS device can be armv6, armv7 or armvs7 platforms.

What is your model of iOS device?

Ronan

**Comment by KwanghoLee** [comment]
Framework was not made only by source uploaded on below site.
Site  Address : https://github.com/introlab/ros_for_ios

So, After installed OS X(MacPorts) for ROS in My System, I compiled Source that you uploaded on githu.com Site.
Compile Result for Framework is Success. However, Compile Link Error is occurred on iPhone4(iOS 6.3.1) when Demo_App is executed

I didin’t fixed the Build Setting Information of Demo_App for Framework Compile

Below is My Build Setting for Demo App
-   Build SDK : iOS 6.1
-   Valid ArchiTectures : arm v7
-   iOS Deployment Target : iOS 6.1

I want to know what point must be fixed or added for Link Error

**Comment by Ronan0912** [comment]
Ok.

I tried with an iPad 3 (A5X) and an iPhone 5 (A6) and the demo_app compiles without any problem.
I don't understand why you installed ROS on OSX in order to execute the ros_for_ios scripts.

I suggest you to start a new clean configuration.
- remove everything concerning ros_for_ios and ROS on OSX (at least delete the path).
- git clone -b master https://github.com/introlab/ros_for_ios.git
- run "sh build.sh"
- Try to compile the demo_app for the simulator and for your iPhone 4

You can also send us the Xcode build log file if there is still the linking problem.

Ronan

**Comment by KwanghoLee** [comment]
As your comment in Site, I performed below Procedure.
• remove everything concerning ros_for_ios and ROS on OSX (at least delete the path).
• git clone -b master https://github.com/introlab/ros_for_ios.git 
• run "sh build.sh"
• Try to compile the demo_app for the simulator and for your iPhone 4
However, Compile Error is still occurred. 
I will attach a error log file and Screen Shot Image.

I think My Computer Device’s Configuration is not matched with yours for Framework Compile.

Please Check  Error Log (You can download : http://211.55.75.193:8080/log.txt)  and Screen Shot Image.
After checking, Please add your comment.

Thank you.
![2013-05-23 10 57 12 2](https://f.cloud.github.com/assets/4476400/552445/d2708d48-c353-11e2-9a33-909d7b771268.png)

**Comment by Ronan0912** [comment]
The log file was very useful. I figured out that you don't have a CMake installation on your system : "cmake: command not found" (I didn't mention that point in the README ... ;-( ). Without this tool, nothing was compiled (the framework contains only the headers files).
You can install CMake on OSX via this link : http://www.cmake.org/cmake/resources/software.html

Ronan
